#!/usr/bin/env python3
import os
import sys
import subprocess

# Add the project to path
project_dir = os.path.expanduser('~/dali-voice-assistant')
os.chdir(project_dir)

# Activate virtual environment
activate_script = os.path.expanduser('~/dali_env/bin/activate_this.py')
if os.path.exists(activate_script):
    exec(open(activate_script).read(), {'__file__': activate_script})
else:
    # Alternative: set PATH and environment
    venv_bin = os.path.expanduser('~/dali_env/bin')
    sys.path.insert(0, venv_bin)
    os.environ['VIRTUAL_ENV'] = os.path.expanduser('~/dali_env')

subprocess.run([sys.executable, 'dali_gui.py'])
